version: "3.8"

services:

  openvpn-server:
    container_name: openvpn-server
    build: .
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./data:/media/openvpn
    ports:
      - "1194:1194/udp"
